# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f5e7d9aaa340871c789d500d5a15d9843c035eb905f565d3d39d5f98c8def592998fe1af07d8b614a9d93042eaf5ddc0fe0d725288b96f5a93f06d3a9a9b050e

test:
  secret_key_base: 26f292392069734e6c19dcda5322eadb7e6d15ae6f4a14e4b1d4a04e31fc8f0a4ef25e563f6b8c81acd2231e13011cbfe4debf51f3be2379b6c543077a81a056

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
